imports:
    #- { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: tool.images.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    #asset_fullImage_folder: 'img/f'
    #asset_mediumImage_folder: 'img/m'
    #asset_smallImage_folder: 'img/t'
    email:
        abuse: ''
        contactCollector:
            - 'test@outlook.com'
            - 'test@live.de'
    #asset_dir: web

salva_jshrink:
    enabled: true # if false {% jshrink %} tag will not compress the content
    flaggedComments: true

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        #isDevSer: 1
        pathTag: t
        pathImage: i
        pathCollection: c
        pathVideo: v
        pathUser: u
        pathImageFull: '%asset_fullImage_folder%'
        pathImageMedium: '%asset_mediumImage_folder%'
        pathImageSmall: '%asset_smallImage_folder%'
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        # the standard distribution overrides this to be true in debug, false otherwise
        auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    AppBundle : ~
                result_cache_driver: apcu
                metadata_cache_driver: apcu
                query_cache_driver: apcu
                second_level_cache:
                    region_cache_driver:
                        type: service
                        id: snc_second_level_cache
                    enabled: true
                    region_lifetime: 3600
                    regions:
                        my_region:
                            lifetime: 3600
                            cache_driver:
                                type: service
                                id: snc_second_level_cache
          #backend:
            #naming_strategy: doctrine.orm.naming_strategy.underscore
            #mappings:
              #BackendBundle : ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

monolog:
    handlers:
        main:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
            # max number of log files to keep
            # defaults to zero, which means infinite files
            max_files: 3
            channels: ['!event']
        filter_for_errors:
            type: fingers_crossed
            # if *one* log is error or higher, pass *all* to file_log
            action_level: error
            handler: file_log

        # now passed *all* logs, but only if one log is error or higher
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error

        # still passed *all* logs, and still only logs error or higher
        syslog_handler:
            type: syslog
            level: error

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            #dsn: redis://localhost
            logging: '%kernel.debug%'
        doctrine:
            type: predis
            alias: doctrine
            #dsn: redis://localhost
            logging: '%kernel.debug%'

    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dmc:'
        result_cache:
            client: doctrine
            entity_manager: default
            namespace: 'drc:'
        query_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dqc:'
        second_level_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dslc:'