# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: user_provider
            form_login:
                login_path:  /login
                check_path:  /login_check
                always_use_default_target_path: true
                default_target_path: /the-cao
                remember_me: true
            logout:
                path: /logout
                target: /
            #guard:
            #    authenticators:
            #        - app.security.login_api_authenticator
            remember_me:
                secret: '%secret%'
                lifetime: 7257600
                path: /
                domain: ~
                always_remember_me: true

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    providers:
        in_memory:
            memory: ~
        user_provider:
            entity:
                class: AppBundle:User